osx_image: xcode7.3
language: objective-c
before_install:
- gem install bundler
- bundle install
- bundle exec pod repo add carambalabs https://github.com/carambalabs/CarambaKit
- git remote set-url origin "https://${GITHUB_TOKEN}@github.com/carambalabs/CarambaKit.git"
script:
- bundle exec fastlane travis
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash scripts/deploy
